(() => {
  const API = 'http://127.0.0.1:8767';
  const css = `
  .pe-fab{position:fixed;right:18px;bottom:18px;z-index:9000;border:1px solid #61706a;background:#151918;color:#a9fbff;padding:11px 15px;font:800 11px Inter,system-ui;letter-spacing:.04em;box-shadow:0 8px 25px #0008}
  .pe-fab:hover{border-color:#58e6ed}.pe-backdrop{position:fixed;inset:0;z-index:9998;background:#000b;display:none;align-items:center;justify-content:center}.pe-backdrop.open{display:flex}
  .pe-panel{width:min(1180px,calc(100vw - 44px));height:min(800px,calc(100vh - 44px));background:#b8bbb7;color:#161918;border:1px solid #626865;box-shadow:0 30px 90px #000d;display:grid;grid-template-rows:52px 1fr}
  .pe-head{display:flex;align-items:center;justify-content:space-between;padding:0 14px;background:linear-gradient(#e7e8e5,#b7bab6);border-bottom:1px solid #686e6a}.pe-head b{font-size:15px}.pe-head small{display:block;color:#4d5551;font-size:9px;margin-top:2px}.pe-close{border:1px solid #666;background:#262b29;color:#fff;width:30px;height:30px}
  .pe-body{display:grid;grid-template-columns:300px 1fr;min-height:0}.pe-listwrap{border-right:1px solid #656b67;background:#202523;color:#edf3f0;padding:10px;overflow:auto}.pe-current{padding:9px;border:1px solid #39413d;background:#121615;margin-bottom:10px;font-size:9px;color:#9ba5a0}.pe-current b{display:block;color:#79f2f8;font-size:11px;margin-top:4px;word-break:break-all}
  .pe-actions{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-bottom:9px}.pe-actions button,.pe-row button{border:1px solid #4d5752;background:#2b312e;color:#eaf0ed;padding:8px;font-size:9px}.pe-item{padding:10px;border:1px solid #343b38;border-bottom:0;background:#171b1a;cursor:pointer}.pe-item:last-child{border-bottom:1px solid #343b38}.pe-item.active{box-shadow:inset 3px 0 #58e6ed;background:#202725}.pe-item b{font-size:11px}.pe-item span{float:right;font-size:8px;color:#92e99c}.pe-item small{display:block;color:#929d98;font-size:8px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .pe-editor{padding:14px;overflow:auto}.pe-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pe-card{border:1px solid #777d79;background:#c6c8c4;padding:11px}.pe-card.full{grid-column:1/-1}.pe-title{font-size:9px;font-weight:900;letter-spacing:.09em;text-transform:uppercase;margin-bottom:9px}.pe-field{display:grid;grid-template-columns:135px 1fr;gap:10px;align-items:center;margin:7px 0;font-size:10px}.pe-field input,.pe-field select,.pe-field textarea{width:100%;border:1px solid #5d6561;background:#1d2220;color:#ecf2ef;padding:8px;font-size:10px}.pe-field textarea{min-height:72px;resize:vertical}.pe-field input[type=checkbox]{width:auto;justify-self:start}.pe-savebar{display:flex;justify-content:space-between;gap:8px;margin-top:12px}.pe-savebar button{padding:9px 12px;border:1px solid #59615d;background:#252b28;color:#edf3f0;font-size:9px}.pe-savebar .primary{border-color:#35c7ce;color:#b9fbff}.pe-savebar .danger{border-color:#8c4e49;color:#ffc5bf}.pe-note{font-size:9px;color:#59615d;margin-top:7px}.pe-toast{position:fixed;z-index:10000;right:22px;top:22px;background:#101413;color:#9cf4f8;border:1px solid #4b5a55;padding:10px 13px;font-size:10px;display:none}.pe-toast.show{display:block}
  `;
  const style = document.createElement('style'); style.textContent = css; document.head.appendChild(style);

  const btn = document.createElement('button'); btn.className='pe-fab'; btn.textContent='PROFILES · v0.5'; document.body.appendChild(btn);
  const toast = document.createElement('div'); toast.className='pe-toast'; document.body.appendChild(toast);
  const root = document.createElement('div'); root.className='pe-backdrop'; root.innerHTML=`<div class="pe-panel"><div class="pe-head"><div><b>Profile Editor</b><small>Automatic per-app behavior · localhost:8767</small></div><button class="pe-close">×</button></div><div class="pe-body"><aside class="pe-listwrap"><div class="pe-current">FOREGROUND APP<b id="pe-current">Waiting for agent…</b><span id="pe-backend"></span></div><div class="pe-actions"><button id="pe-new">+ NEW</button><button id="pe-duplicate">DUPLICATE</button></div><div id="pe-list"></div></aside><main class="pe-editor"><div class="pe-grid"><section class="pe-card full"><div class="pe-title">Identity & Matching</div><div class="pe-field"><label>Name</label><input id="pe-name"></div><div class="pe-field"><label>Enabled</label><input id="pe-enabled" type="checkbox"></div><div class="pe-field"><label>Match app/title</label><textarea id="pe-match" placeholder="firefox\nchromium\nmy project"></textarea></div><div class="pe-savebar"><button id="pe-useapp">USE CURRENT APP</button><span class="pe-note">First matching enabled profile wins.</span></div></section><section class="pe-card"><div class="pe-title">Knob</div><div class="pe-field"><label>Rotate</label><select id="pe-mode"><option value="scroll">Scroll</option><option value="volume">Volume</option></select></div><div class="pe-field"><label>Ctrl + Rotate</label><select id="pe-ctrl"></select></div><div class="pe-field"><label>Shift + Rotate</label><select id="pe-shift"></select></div><div class="pe-field"><label>Alt + Rotate</label><select id="pe-alt"></select></div></section><section class="pe-card"><div class="pe-title">Button Gestures</div><div class="pe-field"><label>Click</label><select id="pe-click"></select></div><div class="pe-field"><label>Double Click</label><select id="pe-double"></select></div><div class="pe-field"><label>Long Press</label><select id="pe-long"></select></div></section></div><div class="pe-savebar"><div><button id="pe-up">↑ PRIORITY</button><button id="pe-down">↓ PRIORITY</button></div><div><button id="pe-delete" class="danger">DELETE</button><button id="pe-save" class="primary">SAVE PROFILE</button></div></div></main></div></div>`; document.body.appendChild(root);

  const $=id=>document.getElementById(id); let snapshot=null, selected='global';
  const actions=['noop','mute','enter','esc','tab','space','playpause'];
  const modes=['inherit','scroll','horizontal_scroll','volume','zoom','tabs'];
  const fill=(id,vals)=>{$(id).innerHTML=vals.map(v=>`<option value="${v}">${v.replaceAll('_',' ')}</option>`).join('')};
  ['pe-click','pe-double','pe-long'].forEach(id=>fill(id,actions)); ['pe-ctrl','pe-shift','pe-alt'].forEach(id=>fill(id,modes));
  const notify=m=>{toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)};
  async function req(path,opt={}){const r=await fetch(API+path,{headers:{'content-type':'application/json'},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||r.statusText);return j}
  function current(){return snapshot?.profiles?.find(p=>p.id===selected)||snapshot?.profiles?.[0]}
  function draw(){if(!snapshot)return; const fg=snapshot.foreground_app||{}; $('pe-current').textContent=fg.app_id||fg.title||'No app detected'; $('pe-backend').textContent=`${fg.backend||'unknown'}${fg.available?' · LIVE':' · fallback'}`; $('pe-list').innerHTML=snapshot.profiles.map(p=>`<div class="pe-item ${p.id===selected?'active':''}" data-id="${p.id}"><b>${p.name}</b>${p.id===snapshot.active_profile?'<span>ACTIVE</span>':''}<small>${p.match?.join(' · ')||'Global fallback'}</small></div>`).join(''); document.querySelectorAll('.pe-item').forEach(el=>el.onclick=()=>{selected=el.dataset.id;draw();loadForm()}); loadForm();}
  function loadForm(){const p=current();if(!p)return;$('pe-name').value=p.name;$('pe-enabled').checked=p.enabled!==false;$('pe-match').value=(p.match||[]).join('\n');$('pe-mode').value=p.mode||'scroll';$('pe-click').value=p.gesture_bindings?.click||'noop';$('pe-double').value=p.gesture_bindings?.double_click||'noop';$('pe-long').value=p.gesture_bindings?.long_press||'noop';$('pe-ctrl').value=p.modifier_modes?.ctrl||'inherit';$('pe-shift').value=p.modifier_modes?.shift||'inherit';$('pe-alt').value=p.modifier_modes?.alt||'inherit';$('pe-delete').disabled=p.id==='global';}
  function payload(){return{name:$('pe-name').value.trim(),enabled:$('pe-enabled').checked,match:$('pe-match').value.split(/\n|,/).map(x=>x.trim()).filter(Boolean),mode:$('pe-mode').value,gesture_bindings:{click:$('pe-click').value,double_click:$('pe-double').value,long_press:$('pe-long').value},modifier_modes:{ctrl:$('pe-ctrl').value,shift:$('pe-shift').value,alt:$('pe-alt').value}}}
  async function refresh(){snapshot=await req('/api/profiles');if(!snapshot.profiles.some(p=>p.id===selected))selected='global';draw()}
  btn.onclick=()=>{root.classList.add('open');refresh().catch(e=>notify(e.message))}; $('.pe-close').onclick=()=>root.classList.remove('open'); root.onclick=e=>{if(e.target===root)root.classList.remove('open')};
  $('pe-save').onclick=async()=>{try{await req(`/api/profiles/${selected}`,{method:'POST',body:JSON.stringify(payload())});await refresh();notify('Profile saved')}catch(e){notify(e.message)}};
  $('pe-new').onclick=async()=>{try{const name='New Profile';const j=await req('/api/profiles',{method:'POST',body:JSON.stringify({name,mode:'scroll',match:[],enabled:true,gesture_bindings:{click:'noop',double_click:'noop',long_press:'noop'},modifier_modes:{ctrl:'inherit',shift:'inherit',alt:'inherit'}})});selected=j.profile.id;await refresh();notify('Profile created')}catch(e){notify(e.message)}};
  $('pe-duplicate').onclick=async()=>{try{const p=current();const copy={...p,id:undefined,name:p.name+' Copy'};const j=await req('/api/profiles',{method:'POST',body:JSON.stringify(copy)});selected=j.profile.id;await refresh()}catch(e){notify(e.message)}};
  $('pe-delete').onclick=async()=>{if(selected==='global')return;try{await req(`/api/profiles/${selected}`,{method:'DELETE'});selected='global';await refresh();notify('Profile deleted')}catch(e){notify(e.message)}};
  $('pe-useapp').onclick=async()=>{try{await req('/api/profiles/use-current-app',{method:'POST',body:JSON.stringify({profile_id:selected})});await refresh();notify('Current app added')}catch(e){notify(e.message)}};
  async function move(dir){const ids=snapshot.profiles.map(p=>p.id),i=ids.indexOf(selected),j=i+dir;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];await req('/api/profiles/reorder',{method:'POST',body:JSON.stringify({order:ids})});await refresh()}
  $('pe-up').onclick=()=>move(-1).catch(e=>notify(e.message)); $('pe-down').onclick=()=>move(1).catch(e=>notify(e.message));
  try{const es=new EventSource(API+'/events');es.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==='profile'||data.type==='profiles_changed'||data.type==='status'){refresh().catch(()=>{})}}}catch(_e){}
})();
